---
- name: Converge
  hosts: all
  tasks:
    - fail: msg=asdfajskfhk
    - name: "Include tasks from set_secret_vault_env"
      include_role:
        name: arpanrec.utils
        tasks_from: tlscert.yml
