---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_instance
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    dockerfile: dockerfile_tls
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 80/udp
      - 80/tcp
    published_ports:
      - 0.0.0.0:8888:80/udp
      - 0.0.0.0:8888:80/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
