---
- name: Converge
  hosts: all
  tasks:
    - name: "Include tasks from set_secret_vault_env"
      include_role:
        name: sourceshift.utils
        tasks_from: set_secret_vault_env.yml

    - name: "Include tasks from add_host_from_vault"
      include_role:
        name: sourceshift.utils
        tasks_from: add_host_from_vault.yml
