---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    # login_cmd_template: 'ssh {instance} -F /tmp/ssh-config'
    ansible_connection_options:
      ansible_connection: local
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
platforms:
  - name: localhost
provisioner:
  name: ansible
  inventory:
    # group_vars:
    #   all:
    #     rv_common_add_host_hostname: vault
    host_vars:
      localhost:
        rv_common_add_host_hostname: vault
verifier:
  name: ansible
